# Generated by Django 4.0.3 on 2022-09-04 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='subject',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
